### ISSUE TITLE
Oracle CLOB throws error ORA-00932: inconsistent datatypes: expected CLOB got CHAR

### ISSUE THREAD

**Issue by smpawar** [GoogleCloudPlatform/professional-services-data-validator#1001]
e.g. syntax.

data-validation validate row -sc MY_ORACLE_CONN -tc MY_POSTGRES_CONN -tbls <tablename>-pk <pk_details>--concat "*"

sqlalchemy.exc.DatabaseError: (cx_Oracle.DatabaseError) ORA-00932: inconsistent datatypes: expected CLOB got CHAR

**Comment by smpawar** [comment]
Using hash gives this error

sqlalchemy.exc.DatabaseError: (cx_Oracle.DatabaseError) ORA-00904: "STANDARD_HASH": invalid identifier

**Comment by helensilva14** [comment]
Hi @smpawar! Could you please check if this documentation here helps you https://github.com/GoogleCloudPlatform/professional-services-data-validator/tree/develop/samples/oracle#data-validation-of-oracle-blob even though it was written specifically for BLOB?

CC @nj1973 for visibility

**Comment by helensilva14** [comment]
Hi @smpawar, any updates regarding this issue? Thanks!

**Comment by smpawar** [comment]
checking..

**Comment by smpawar** [comment]
@helensilva14 DBA gave the grant to the user. It didn't help. Still getting ORA-00932

**Comment by nj1973** [comment]
Hi @smpawar,

I presume your Oracle version is 11g or earlier? For hashing we rely on Oracle's STANDARD_HASH function which only became available from 12c onwards.

The `ORA-00932: inconsistent datatypes: expected CLOB got CHAR` is a trickier issue to resolve, it comes from a COALESCE expression.

There are few things you can try here:

- You could run your command without the CLOB column to validate the non-CLOB columns by replacing `--hash="*"` with a CSV of your columns, e.g. `--hash=col1,col2,col4`.
- You could use `--comparison-fields` instead of `--concat`/`--hash`
- You could follow the instructions Helen provided previously to validate CLOB columns by hash by using the DBMS_CRYPTO package. I have created an issue for myself to update that doc to cover CLOB more explicitly. https://github.com/GoogleCloudPlatform/professional-services-data-validator/issues/1028

**Comment by helensilva14** [comment]
Following up this issue: Hi @smpawar, were you able to check Neil's comment below and try the options? Please let us know so we can close the issue or continue checking the problem, thanks!

**Comment by smpawar** [comment]
@nj1973 @helensilva14 Yes it was working with --hash="*". Thanks! My bad, to miss updating here.
