### ISSUE TITLE
Teradata SSLMODE support - connection timeout

### ISSUE THREAD

**Issue by jcqpinto** [GoogleCloudPlatform/professional-services-data-validator#1011]
When connecting to Teradata, for connections that require SSLMODE=DISABLE, there is a i/o timeout error, since data-validation tool tries to connect to port 443 instead of standard 1025 port, even if --port 1025 option is provided.

Looks like there is no option available to set SSLMODE and prevent this issue.

<img width="867" alt="image" src="https://github.com/GoogleCloudPlatform/professional-services-data-validator/assets/22936830/94972d63-c77b-4e37-a9f2-9e015bc52f76">

**Comment by sundar-mudupalli-work** [comment]
Hi,

DVT uses [teradatasql](https://pypi.org/project/teradatasql/#ConnectionParameters). I don't know exactly why DVT is connecting on port 443 even though port 1025 is provided. Looking at the Connection Parameters, my guess is that the customer's Teradata instance has SSL enabled and the default mode with teradatasql is SSLMODE=PREFER. Therefore the connection prefers the secure port.

The fix to this is a bit complicated and requires a code change. Teradata connections can take a lot of different parameters and it is difficult for DVT to handle all the different parameters. The recommended option is to allow users to specify a JSON string in their environment that can be passed on to the `teradatasql.connect` call along with the arguments that are in the DVT connection. Please see [using the driver](https://pypi.org/project/teradatasql/#Using) regarding how to do this. The environment variable could be called `PSO_DV_TERADATA_CONFIG` or something similar - we already use an environment variable `PSO_DV_CONFIG_HOME`. The same situation is a lot easier (i.e. no changes to DVT code required) in PostgreSQL because the PostgreSQL library `libpq` reads connection parameters from environment variables. See [libpq Environment Variables](https://www.postgresql.org/docs/current/libpq-envars.html).

Sundar Mudupalli

**Comment by jcqpinto** [comment]
That's right, `teradatasql.connect` can receive parameters as a JSON string, or even combined (kwargs + JSON). Including a new optional argument, such as `--json-params`, for Teradata connection configuration, and use it in `teradatasql.connect` call, could solve the issue and would be flexible enough to support additional useful connection parameters, without doing a lot of code changes.

**Comment by jcqpinto** [comment]
Created PR with working solution. Additional parameter `--json-params` added for Teradata connection configuration.

User can add additional teradatasql connection options by providing JSON string, like `--json-params "{'sslmode': 'disable', 'encryptdata': 'true'}"`

**Comment by helensilva14** [comment]
That's super great, thanks a lot @jcqpinto for your proactive contribution, we really appreciate it! 

@nehanene15 could you please take a look at this issue and the linked PR #1014? It LGTM to me and all checks passed!

**Comment by helensilva14** [comment]
PR merged to develop, closing this issue and thanks again @jcqpinto!
