### ISSUE TITLE
find-tables not working

### ISSUE THREAD

**Issue by mahurtado** [GoogleCloudPlatform/professional-services-data-validator#1017]
We are running an homogeneous migration: AWS RDS Postgres 12.14 to Google Cloud SQL AlloyDB.

After running migration with DMS, when checking with Data Validation Tool, as explained [here](https://cloud.google.com/database-migration/docs/oracle-to-postgresql/verify-migration#verifying-using-DVT), we can create connections, but running **find-tables** return an empty result.

Running with verbose mode gives no extra info.

UPDATE: Correction in my initial statement - This is a heterogeneous migration: **AWS RDS Oracle 12.14 to Google Cloud SQL AlloyDB**.

**Comment by nj1973** [comment]
Information for whoever picks this up first.

There appears to be two problems here.

**1) Oracle list_tables()**
The list of Oracle tables is not being given a schema and is defaulting to finding tables in the schema of the user specified in the connection. I was able to get a correct list of tables from an Oracle connection by making this change:
```
 def list_tables(client, schema_name):
     """Return a list of tables in the DB schema."""
-    if client.name in ["oracle", "postgres", "db2", "mssql", "redshift", "snowflake"]:
+    if client.name in ["postgres", "db2", "mssql", "redshift", "snowflake"]:
         return client.list_tables()
     return client.list_tables(database=schema_name)
```

**2) PostgreSQL list_tables()**
This is giving us table names prefixed with the database name rather than the schema name. The database is in the connection configuration so I don't think we want to look in other databases, we should be prefixing with schema (I think).
Plus the actual list of table names is taken from the public schema of the database in the connection config, which is then prefixed with each database in the PostgreSQL instance.
This produces output that will rarely be correct.

**3) Tests**
I guess a third problem is the absence of `find-tables` testing.

**Comment by helensilva14** [comment]
Thanks a lot for the quick initial analysis @nj1973!

Hi @mahurtado, I was wondering if you tested reducing the cutoff parameter, as we mention here https://github.com/GoogleCloudPlatform/professional-services-data-validator#building-matched-table-lists?

It would be something like below. Just wanted to make sure if this might be related or not, could you please try it and let us know your result? Thanks!

```
data-validation find-tables --source-conn source --target-conn target \
    --allowed-schemas pso_data_validator \
    --score-cutoff 0.7
```

**Comment by mahurtado** [comment]
Hello,
Thank you @helensilva14 , yes we test with several values of **score-cutoff.** Same (empty) result.

**Comment by mahurtado** [comment]
Correction in my initial statement:


This is a **heterogeneous** migration: AWS RDS **Oracle** 12.14 to Google Cloud SQL AlloyDB.

**Comment by helensilva14** [comment]
Thanks for your response @mahurtado, we started to investigate this issue

**Comment by nj1973** [comment]
@helensilva14 , based on this https://dba.stackexchange.com/a/127668 page I think the SQL below would be good for listing schemas on PostgreSQL:

```
SELECT nspname
FROM pg_catalog.pg_namespace
WHERE nspname !~ '^pg_'
AND nspname <> 'information_schema'
ORDER BY 1;
```

**Comment by helensilva14** [comment]
Hi @mahurtado! Sorry for the lack of updates, but we just merged to develop a fix for your problem, it was a bug indeed. So please check it out and if it does not work for you please re-open this issue.
Thanks again for reaching out!

**Comment by mahurtado** [comment]
Great, thank you!
