### ISSUE TITLE
validate column: error handling a very large timestamp '9999-12-31 23:59:59'

### ISSUE THREAD

**Issue by dominikhron** [GoogleCloudPlatform/professional-services-data-validator#1053]
I have found that a `--max` column comparison on a very large timestamp returns an error. This is an issue specifically for our implementation of SCD, where we use the future **timestamp '9999-12-31 23:59:59'** to indicate that a record has not been closed yet. Below is data to help you reproduce the error between Teradata and BigQuery. I suspect this error will happen for any system. 

Data preparation in **Teradata**:

```sql
DROP TABLE CZ_TST_NUCLEUS.DVT_TIMESTAMP_VALIDATION;

CREATE TABLE CZ_TST_NUCLEUS.DVT_TIMESTAMP_VALIDATION
(
	min_timestamp_col TIMESTAMP(6),
	avg_timestamp_col TIMESTAMP(6),
	max_timestamp_col TIMESTAMP(6)
);

INSERT INTO CZ_TST_NUCLEUS.DVT_TIMESTAMP_VALIDATION
VALUES (timestamp'2018-03-21 00:00:00',timestamp'2018-03-21 00:00:00',timestamp'2018-03-21 00:00:00');

INSERT INTO CZ_TST_NUCLEUS.DVT_TIMESTAMP_VALIDATION
VALUES (timestamp'1900-01-01 00:00:00',timestamp'2018-03-21 00:00:00',timestamp'9999-12-31 23:59:59');
```

Data preparation in **BigQuery**:

```sql
drop table vfcz_dh_edw_adhoc_dev_01_s.dvt_timestamp_validation;

create table vfcz_dh_edw_adhoc_dev_01_s.dvt_timestamp_validation
(
  min_timestamp_col timestamp,
  avg_timestamp_col timestamp,
  max_timestamp_col timestamp
);

insert into vfcz_dh_edw_adhoc_dev_01_s.dvt_timestamp_validation
values (timestamp'2018-03-21 00:00:00',timestamp'2018-03-21 00:00:00',timestamp'2018-03-21 00:00:00');

insert into vfcz_dh_edw_adhoc_dev_01_s.dvt_timestamp_validation
values (timestamp'1900-01-01 00:00:00',timestamp'2018-03-21 00:00:00',timestamp'9999-12-31 23:59:59');
```

I tried running the following data validation command on the above data:

```
data-validation validate custom-query column -sc MY_TD_CONN -tc MY_BQ_CONN --source-query "SELECT CAST(min_timestamp_col AS TIMESTAMP) AS min_timestamp_col, CAST(avg_timestamp_col AS TIMESTAMP) AS avg_timestamp_col, CAST(max_timestamp_col AS TIMESTAMP) AS max_timestamp_col FROM CZ_TST_NUCLEUS.DVT_TIMESTAMP_VALIDATION" --target-query "SELECT DATETIME(min_timestamp_col) AS min_timestamp_col, DATETIME(avg_timestamp_col) AS avg_timestamp_col, DATETIME(max_timestamp_col) AS max_timestamp_col FROM vfcz_dh_edw_adhoc_dev_01_s.dvt_timestamp_validation" --min min_timestamp_col,avg_timestamp_col,max_timestamp_col --max min_timestamp_col,avg_timestamp_col,max_timestamp_col
```

This command gives the error `TypeError: Cannot change data-type for object array.`

I am sure that the timestamp I mentioned is causing this error. When I exclude the **max_timestamp_col** from the `--max` flag, the data validation command runs successfully.

**Comment by nj1973** [comment]
Research

The problem is because Pandas uses Numpy's `datetime64` type with nanosecond precision, this in turn supports a maximum value of 2262-04-11. Using a precision more granular than nanosecond increases the range of `datetime64` beyond year 9999. I believe we have this problem across all supported engines.

Pandas v2.0.0 implemented support for non nanosecond precisions, https://pandas.pydata.org/docs/dev/whatsnew/v2.0.0.html#other-api-changes:

_Passing a np.datetime64 object with non-nanosecond resolution to Timestamp will retain the input resolution if it is “s”, “ms”, “us”, or “ns”; otherwise it will be cast to the closest supported resolution (GH 49008)_

I've tried the test case (nice test case btw @dominikhron) included above using Pandas > 2.0.0 and the problem persists.

The entry point from DVT code is here: 
https://github.com/GoogleCloudPlatform/professional-services-data-validator/blob/c2b660b4f63a1fe1ca1dd258ff943f16b866e4b2/data_validation/data_validation.py#L298C1-L298C1

I forced the BigQuery schema in Ibis to use `datetime64[ms]` instead of `datetime64[ns]` but still see a raise of `OutOfBoundsDatetime` in the debugger referencing `ns`:

```
pandas._libs.tslibs.np_datetime.OutOfBoundsDatetime: Cannot cast 9999-12-31 23:59:59+00:00 to unit='ns' without overflow.
```

More investigation required. The Ibis code in the area has changed in recent versions so we might get lucky from an Ibis upgrade. I need to create a test case and try it on a newer Ibis version.

This is tricky because we are at the mercy of external factors.
