### ISSUE TITLE
Getting MemoryError for bigger tables(numpy.core._exceptions._ArrayMemoryError)

### ISSUE THREAD

**Issue by pavannadgoudar** [GoogleCloudPlatform/professional-services-data-validator#1144]
Table is big so we tried with comparing only 2 columns still we are getting memory error.

Command : data-validation validate row --source-conn MSSQL --target-conn BQ --tables-list <SourceTableName>=<TargetTableName> --filter-status fail --primary-keys <primaryKey> -comp-fields <CmpField1>,<CmpField2> --bq-result-handler <project>.<dataset>.DVT_RESULTS --filters <SNAPSHOT_DATE> ='2024-01-10'

Error from command : numpy.core._exceptions._ArrayMemoryError : Unable to allocate <number> GiB for an array with shape(<number>,<number>) and data type object

Table Volume : 2.5L records and 216 Columns

**Comment by nehanene15** [comment]
Memory constraints can occur for large row validations since each row needs to be brought into memory to compare source and target values. For large tables, you will likely need to use the [Scaling DVT](https://github.com/GoogleCloudPlatform/professional-services-data-validator?tab=readme-ov-file#scaling-dvt) approach by generating table partitions and then distributing that (optional). 

You can also increase the machine size, but that won't be a feasible fix for very large tables.

**Comment by pavannadgoudar** [comment]
Thank you very much @nehanene15 . This information is helpful. I think scaling needs an additional infra level changes. We will initiate this discussion to check feasibility on GKE/Cloud Run Jobs.

**Comment by nehanene15** [comment]
Sounds good. I will close this issue and feel free to open another if you encounter a bug when using the Cloud Run approach.
