### ISSUE TITLE
Exception in PostgreSQL row validation for table with many columns

### ISSUE THREAD

**Issue by nj1973** [GoogleCloudPlatform/professional-services-data-validator#1216]
Exception in PostgreSQL row validation for table with many columns:
```
sqlalchemy.exc.OperationalError: (psycopg2.errors.TooManyArguments) cannot pass more than 100 arguments to a function

LINE 222: ...per__dvt_calc_col_103 AS upper__dvt_calc_col_103, concat_ws(...
```

I was able to reproduce this easily enough on PostgreSQL but also had problems with Oracle:
```
    cursor.execute(statement, parameters)
cx_Oracle.DatabaseError: ORA-01489: result of string concatenation is too long
```

I wonder if we should break up validations with > 100 columns into multiple validations and not try to manipulate complex concat expressions for each supported engine. The down side to this would be multiple hashes for each primary key. Needs some discussion.

**Comment by sundar-mudupalli-work** [comment]
Neil,

I agree that this could be tackled. See bug report [here](https://github.com/GoogleCloudPlatform/professional-services-data-validator/issues/897). I know one other customer here on the west coast had huge issues with large number of columns (over 4000). My arrogant response then (and somewhat now) is that every system has a limit. However, I think DVT can address this.

DVT is set up so that multiple validations in one .yaml file run concurrently. One option is to set up DVT so that when the number of columns is large - we throw out a message saying - "exceeded xx columns", recommend the customer user the config file option. With the config file option, we can split the validations into a sequence of validations one after the other. We can put all the validations in one yaml file. We already have code to write multiple validations into one output file - see [PR 1178](https://github.com/GoogleCloudPlatform/professional-services-data-validator/pull/1178). One thing I have noticed is that the run id for the second and third validation in BQ is different even if they are from the same yaml file. Perhaps this can be changed to share one run id - will make post processing results easier.

Let me know what you think.

Sundar Mudupalli

**Comment by nj1973** [comment]
My initial thought was that we have an example of a single command breaking out into multiple validations already when the user provides multiple table names, in `cli_tools.get_pre_build_configs()`. We could have a further check in this method for when the number of row validation columns might exceed our limit, example pseudo code below (untested - just thinking it through):

```
    if getattr(args, "concat", None) == "*" or getattr(args, "hash", None) == "*":
            _source_ibis_cols = clients.get_ibis_table_schema(
                source_client, table_obj["schema_name"], table_obj["table_name"]
            )
            if len(_source_ibis_cols) > consts.CONFIG_MAX_CONCAT_COLUMNS:
                for col_chunk in split_list_to_sublists(
                    _source_ibis_cols.names, consts.CONFIG_MAX_CONCAT_COLUMNS
                ):
                    col_csv = ",".join(col_chunk)
                    pre_build_configs_copy = copy(pre_build_configs)
                    concat_override = col_csv if args.concat == "*" else args.concat
                    hash_override = col_csv if args.hash == "*" else args.hash
                    pre_build_configs_copy["concat"] = concat_override
                    pre_build_configs_copy["hash"] = hash_override
                    pre_build_configs_list.append(pre_build_configs_copy)
            else:
                pre_build_configs_list.append(pre_build_configs)
        else:
            pre_build_configs_list.append(pre_build_configs)
```

I think something like that would work for both validations to config and immediate validations and not require the user to manually intervene. But I might have missed something.

**Comment by nj1973** [comment]
I've created a test table with 400 columns on the feature branch. This validates fine on Teradata and BigQuery. I need to cap it 100 columns at a time for PostgreSQL and somewhere between 100-150 for Oracle.

This adds weight to not having a single limit across all engines but having some variance/control.

I'm thinking we could use an option for the limit (e.g. `--max-concat-columns`) but only give it a default (probably of 100) for PostgreSQL and Oracle, other systems would be unlimited.

And as we find further limits in the future we can amend the defaults and suggest users use `--max-concat-columns` as a workaround.

Any comments @nehanene15 , @sundar-mudupalli-work ?

**Comment by sundar-mudupalli-work** [comment]
Neil,

DVT is pretty complex - my preference is to choose defaults that work for everyone out of the box. If customers want to fine tune things, then they can learn the complexity.

I am comfortable choosing a single reasonable default (say 50) that works across all engines. We could print a warning message saying - validation includes more than 50 columns. Splitting into n validations - consider using `--max-val-columns` for greater control of the validations.

Thanks.

Sundar Mudupalli

**Comment by nehanene15** [comment]
I think there should be a flag - it's always better to provide the user an option to configure this value especially since it differs per database.  This is also very dependent on how much data is stored per column. In the past some customers have hit this issue at 70 columns and others at 140.

Related issue: Issue #897 specifically the 'recursion depth exceeded' error has been reported - in this case even with BQ to BQ validations.

**Comment by sundar-mudupalli-work** [comment]
Hi,

I am not disagreeing about the need for a flag. I suggest we pick a default number of columns to split the validation into multiple validations so that DVT works out of the box when large number of columns are specified.  Our customer on the west coast will love this fix!!

Sundar Mudupalli

**Comment by nj1973** [comment]
SQL Server has a hard limit like PostgreSQL:
```
E       sqlalchemy.exc.ProgrammingError: (pyodbc.ProgrammingError) ('42000', '[42000] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]The concat function requires 2 to 254 arguments. (189) (SQLExecDirectW)')
```

Snowflake successfully validated my 400 column test table.

MySQL successfully validated my 400 column test table.

Of the systems tested, based on the 400 column test table and the product versions for our integration tests, we have:

```
System        Limit     Notes
------------- --------- ---------------------------------
BigQuery      Unknown   Tested 400 successfully
MySQL         Unknown   Tested 400 successfully
Oracle        100(ish)  soft limit based on data types
PostgreSQL    99        hard limit
SQL Server    254       hard limit
Teradata      Unknown   Tested 400 successfully
```

I didn't test Hive or Spanner.

I'm hesitant to default to a low/safe limit because each time we break up a validation we have an extra query to run. So if I'm validating a 10 million row table with 400 columns and a safe limit of 50 columns then I'll actually run 8 queries on my big(ish) table which could upset a Teradata/BigQuery customer because they could do it all in one query.

For this reason I propose to only have caps (via defaulting the option) on systems that we know have a limit:

Oracle: 100
PostgreSQL: 99
SQL Server: 254

And the others remain uncapped until someone highlights a limit we don't currently know about. When they do we have a workaround in the `--max-concat-columns` option and an easy fix to add another default to a dict constant.
