### ISSUE TITLE
Fix known ibis-framework vulnerability

### ISSUE THREAD

**Issue by nick-redfearn** [GoogleCloudPlatform/professional-services-data-validator#1227]
See [here](https://github.com/GoogleCloudPlatform/professional-services-data-validator/blob/develop/setup.py#L36)

The validator is dependent on ibis-framework version 5.1.0

This library version has a known vulnerability -> https://github.com/advisories/GHSA-x563-6hqv-26mr

Can this be fixed please?

**Comment by helensilva14** [comment]
Hi @nick-redfearn, thank you very much for letting us know!

Unfortunately we still need to do lots of manual changes to upgrade the Ibis usage in our code because we created implemented customizations on top of it, so the change to Ibis beyond v5.1.0 it is still in our backlog at the moment at #931.

**Comment by helensilva14** [comment]
Closing as duplicate of #931, since the action here is upgrading Ibis version itself
