### ISSUE TITLE
Error validating Postgres using Custom Query "permission denied to create temporary tables"

### ISSUE THREAD

**Issue by madhu-jain** [GoogleCloudPlatform/professional-services-data-validator#1261]
Customer is trying to run below command for performing row validation between Postgres and Teradata using Custom query : 

data-validation -v validate custom-query row \
--source-conn pg_qa \
--target-conn tera_qa \
--source-query-file Z0005_PG.sql \
--target-query-file Z0005_TD.sql \
--primary-keys ID \
-comp-fields agreementId,decisionStatus,rejectionReason,approvalExpiryDate,decisionDate,etlLogId

They're getting error as : 
sqlalchemy.exc.ProgrammingError: (psycopg2.errors.InsufficientPrivilege) **permission denied to create temporary tables in database "fcealfa_ods"**

[SQL: CREATE TEMPORARY VIEW "9f9ee039688446228a7cd00db332f08c" AS SELECT  id,  agreementId,  decisionStatus,  rejectionReason,  approvalExpiryDate,  decisionDate,  etlLogId FROM public.EodAgreementCreditDecision]

Seems while validating between Postgres and TD, DVT creates a temporary table on Postgres DB to fetch schema. 

Since Postgres is Source for Customer, it's difficult for them to get create table permissions there. 
Requesting a solution for the same.

**Comment by helensilva14** [comment]
Bringing @sundar-mudupalli-work's idea here to have it registered for reference:

- _It may be possible to not create a temporary table for custom query row validation. Currently it happens on https://github.com/GoogleCloudPlatform/professional-services-data-validator/blob/develop/third_party/ibis/ibis_postgres/client.py#L83 using `con.exec_driver_sql(f"CREATE TEMPORARY VIEW {name} AS {query}")`_

- _We may be able to instead use `SELECT * from {query} limit 0` and the second answer in this StackOverflow question seems to be able to get the column types from a select query -> https://stackoverflow.com/questions/37478323/how-to-programatically-get-table-structure-with-pyscopg2_

**Comment by sundar-mudupalli-work** [comment]
Hi,

Creating the test case for demonstrating this problem is quite challenging. I have done it and here are the steps.

1. Permission to create temporary tables are given at a database level. So you need a separate database that has this permission denied. I created a database `notemp` where I revoked this permission (public gets permission by default). Because it is a separate database, you need to add a separate postgres connection for the `notemp` database.
2. Create the schema `read_only` and a simple table in the schema `simple`. You may have to grant usage privileges in the schema `read_only` to the user. You should also grant select on all tables in the schema to the user.
3. Confirm the permissions of the database in `psql` using `\l notemp`, the schema by `\dn+ read_only` and the table by `\dp read_only.simple`

Since Temporary permissions are denied for this DVT connection (user and database combo) - this bug can be demonstrated.

Sundar Mudupalli
