### ISSUE TITLE
Labels on the Bigquery queries used by DVT

### ISSUE THREAD

**Issue by Rushikesh-Hande** [GoogleCloudPlatform/professional-services-data-validator#1266]
Hello Team,

Do we have facility to add labels for Bigquery query used in DVT or could that feature be added? 

Thanks in advance

**Comment by helensilva14** [comment]
Hello! DVT already has a parameter to pass labels to the validation executions as it is used as follows:

```
  [--labels or -l KEY1=VALUE1,KEY2=VALUE2]
                        Comma-separated key value pair labels for the run.
```

When saving results to BQ, labels are stored there as well.

**Comment by Rushikesh-Hande** [comment]
Thanks @helensilva14 for checking on this and clarification. DVT guide helps in understanding addition of labels which will be stored in dvt results table if used. 

But I am looking for the labels which will be tagged to the Bigquery queries and stored in the BQ metadata tables like INFORMATION_SCHEMA.JOBS. For example even if I add labels through option provided by DVT, it will not be showcased in the query in attached image 
<img width="885" alt="image" src="https://github.com/user-attachments/assets/899e5402-fcbd-438b-ae40-c1d8e9044120">

Please help in clarification if I am missing anything.

**Comment by helensilva14** [comment]
Hello! As explained in our call, unfortunately we can not set BQ native job labels (INFORMATION_SCHEMA.JOBS) since we use Ibis as our backend interface (https://ibis-project.org/backends/bigquery) and there's no parameters available to provide this configuration.  Most I could find was this https://cloud.google.com/bigquery/docs/adding-labels#adding-label-to-session, but then it would be needed a completely new approach in DVT to be able to pass this information when connecting to BQ.

I'll close this issue for now as not planned.
