### ISSUE TITLE
Row Validations(cell by cell) validation inserting many records in result Bigquery table

### ISSUE THREAD

**Issue by Rushikesh-Hande** [GoogleCloudPlatform/professional-services-data-validator#1267]
Hello Team,

Is there any way, we could insert one consolidated summary record as a success or failure for complete Row validations(cell by cell) validation?

**Comment by helensilva14** [comment]
Hello! Unfortunately this is not possible, since each row validation is an operation by itself so we do need to store all of them separately.

But you could create a SQL view on top of the results table to get an aggregated/consolidated status for all row validations executed for one given table name.

**Comment by Rushikesh-Hande** [comment]
Sure, thanks for the clarification @helensilva14
