### ISSUE TITLE
Custom Query Validation for Teradata

### ISSUE THREAD

**Issue by srikanthgaddam2** [GoogleCloudPlatform/professional-services-data-validator#458]
Source - Teradata
Target - Big Query
python3 -m data_validation -v validate custom-query --source-query-file AC_CUSTOMER_TD.sql --target-query-file AC_CUSTOMER_BQ.sql -sc Boeing_TD_CONN -tc Boeing_BQ_CONN -tbls "xxxxxx.xxxxx= xxx.xxxx" -bqrh boeing-dev-bcdap-dataops.METADATA.DVT_RESULTS

When executed the validation the source sql that is parsed has count (not in quotes) which a keyword and it is causing the validation to fail.

error -

pandas.io.sql.DatabaseError: Execution failed on sql 'SELECT * FROM (SELECT count(*) as count FROM (SELECT MAJOR_MODEL,COUNT(*)
FROM BCDW_IUT_NONCORE_T.GA_VALID_PIN_MODEL_ENGR
GROUP BY MAJOR_MODEL) as base_query) t0 SAMPLE 0': [Version 17.10.0.6] [Session 2266074] [Teradata Database] [Error 3707] Syntax error, expected something like a name or a Unicode delimited identifier between the 'as' keyword and the 'count' keyword.

**Comment by kanhaPrayas** [comment]
@srikanthgaddam2  Can you share sample TD sql and BQ sql. It will be easier to rerun the use case and debug.

**Comment by kanhaPrayas** [comment]
The command specified in the issue:
`python3 -m data_validation -v validate custom-query --source-query-file AC_CUSTOMER_TD.sql --target-query-file AC_CUSTOMER_BQ.sql -sc Boeing_TD_CONN -tc Boeing_BQ_CONN -tbls "xxxxxx.xxxxx= xxx.xxxx" -bqrh boeing-dev-bcdap-dataops.METADATA.DVT_RESULTS`

This is an invalid command

**Comment by mokhahmed** [comment]
since count is a reserved keyword at teradata. we need to apply the below workaround to fix this issue. 

1. At [custom_query_builder.py](https://github.com/GoogleCloudPlatform/professional-services-data-validator/blob/97c320341dc6d17fc390fcd2dc503ab2411cab57/data_validation/query_builder/custom_query_builder.py#L26)

you need to add a suffix to to the agg_type eg. `count  --> count__all` to avoid reserved words issue  

```
  def get_aggregation_query(self, agg_type, column_name):
        """Return aggregation query"""
        aggregation_query = ""
        if column_name is None:
            aggregation_query = f"{agg_type} (*) as {agg_type}__all,"
        else:
            aggregation_query = f"{agg_type} ({column_name}) as {agg_type}__{column_name},"
        return aggregation_query
```

2. At [data_validation.py ](https://github.com/GoogleCloudPlatform/professional-services-data-validator/blob/97c320341dc6d17fc390fcd2dc503ab2411cab57/data_validation/data_validation.py#L310)

you need to revert the prefix back after executing the query at the source/target clients to avoid any compatibility issue 

```
 if process_in_memory:
            source_df = self.config_manager.source_client.execute(source_query)
            target_df = self.config_manager.target_client.execute(target_query)
            
            source_df.rename(columns={"count__all": "count"}, inplace = True)
            target_df.rename(columns={"count__all": "count"}, inplace = True)
```
