### ISSUE TITLE
I request that Sybase be supported.

### ISSUE THREAD

**Issue by bnb012008** [GoogleCloudPlatform/professional-services-data-validator#463]
I request that Sybase be supported.

**Comment by nehanene15** [comment]
We use SQL Alchemy to connect to SQL Server, which could be modified to support Sybase: https://docs.sqlalchemy.org/en/14/dialects/sybase.html#module-sqlalchemy.dialects.sybase.pyodbc

[This line](https://github.com/GoogleCloudPlatform/professional-services-data-validator/blob/develop/third_party/ibis/ibis_mssql/client.py#L83) would have to be updated to the correct URL `sybase+pyodbc` instead of `mssql+pyodbc`
