### ISSUE TITLE
Numeric overflow for count on big TERADATA table

### ISSUE THREAD

**Issue by RithyG** [GoogleCloudPlatform/professional-services-data-validator#480]
Hello,
When comparing big tables in TERADATA, we are faced with the error : "Numeric overflow ocurred during computation".
Is there anyway to introduce the possibility to cast the result of the count as BIGINT ?
Like it is explained here :
https://support.teradata.com/community?id=community_question&sys_id=0ab607ef1b57fb00682ca8233a4bcbbd
BR,

**Comment by nehanene15** [comment]
Yes, you can do so via YAML in this example:
https://github.com/GoogleCloudPlatform/professional-services-data-validator/blob/develop/docs/examples.md#sample-yaml-with-calc-fields-cast-to-numeric-before-aggregation
Here, instead of casting to `decimal(38,9`) you can cast to `int64` (BIGINT)

You can also use the `--cast-to-bigint` flag in the CLI: https://github.com/GoogleCloudPlatform/professional-services-data-validator#column-validations

**Comment by RithyG** [comment]
Hello, thank you for your answer. Sadly I have an error with this argument in the CLI.
data-validation: error: unrecognized arguments: --cast-to-bigint

**Comment by nehanene15** [comment]
This change is in the develop branch and will be pushed in the next release. You can pull the most recent changes in develop with `pip install . `
