### ISSUE TITLE
Group by multi column is missing the source table name

### ISSUE THREAD

**Issue by aaslam17** [GoogleCloudPlatform/professional-services-data-validator#518]
When we do a group-by on multiple columns with oracle as target and bigquery as source, the result doesnot contain the source table name if the group value is not present in the bigquery source.

Attached screenshot
https://screenshot.googleplex.com/7W9gwtcQVE653uM

**Comment by helensilva14** [comment]
Hi @aaslam17! We worked on this item and **when the specific row exists on the:**
- Target table and doesn't exist on source: we did find a way to bring the source table name, you can see the changes on [this commit here](https://github.com/GoogleCloudPlatform/professional-services-data-validator/commit/0d17fe6c2ca1eb1a8e17922b98f8a69ad1f1d766)
- Source table and doesn't exist on target: we still kept getting the target table name as null

This would require more analysis and as a matter of priority, we will close this issue for now, since this is not critical. 
Thank you for pointing it out!
