### ISSUE TITLE
DVT scaling to noSQL database

### ISSUE THREAD

**Issue by GayathriRipple** [GoogleCloudPlatform/professional-services-data-validator#568]
Adding validation to noSQL database will be really helpful.

I created a hive external table on top of hbase, and validated the hbase data pointed by hive.
That failed in ibis with the following error:
  File "python3.9/site-packages/ibis/backends/impala/client.py", line 263, in _wait_synchronous
    raise OperationalError("Operation is in ERROR_STATE")
impala.error.OperationalError: Operation is in ERROR_STATE

Kindly let me know if there is a way to fix this.
Does the tool support HBASE data validation, am I missing something here? Thanks!

**Comment by nehanene15** [comment]
The tool does not support HBASE or any NoSQL database currently. This is because we rely on the relational schema model and the [Ibis framework](https://ibis-project.org/docs/3.1.0/) to generate SQL queries that validate the data is matching between source and target.

**Comment by GayathriRipple** [comment]
Sure thank you!

I would like to know one other thing about the tool.
I am sure you would have conducted a performance test for huge data volume,
would you be able to share some details around the same - say the time taken by this tool to validate higher data volumes, whatever volume you considered for the testing. Thanks!

**Comment by nehanene15** [comment]
We don't have exact numbers to share since it is dependent on the what type of validations you are running and the size of the tables. When you enable verbose output (`--verbose`), you can view the SQL queries DVT generates and runs on the source and target system. The more data these queries scan and output, the longer it will take. Also keep in mind that row validation will require memory to store each row you are validating - therefore we recommend using random row or filters instead of validating the whole table.

We also have examples to scale DVT with [Cloud Run](https://github.com/GoogleCloudPlatform/professional-services-data-validator/tree/develop/samples/run) or [Airflow](https://github.com/GoogleCloudPlatform/professional-services-data-validator/tree/develop/samples/airflow).

**Comment by GayathriRipple** [comment]
Sure, that helps.
Thank you!
