### ISSUE TITLE
Determine the method for generating batches efficiently

### ISSUE THREAD

**Issue by renzokuken** [GoogleCloudPlatform/professional-services-data-validator#619]
Sub-issue of issue #598 

The fastest solution will be to use a MIN/MAX split of a numeric primary key and compute the batches external to the database in order to generate config files for efficient partitioned execution.

Longer term we may need to look into more complex solutions such as RANK_ORDER and MOD division in order to generate batches across combo analytical keys.

Exit criteria for this ticket should be the generation of multiple YAML files that contain partitioned filters.

**Comment by mohdt786** [comment]
TODO:
1. Methods to save the partitions?:
   i. Ask user for config-folder instead of config-file and group YAMLs per table(Have multiple YAML config files)
   ii. Save all the partitions in the same config file per table (One YAML config file per table)
   iii. Save all the partitions in the same config file for all the tables (Single YAML file for all tables)
2. Add partition filter with existing filter specified by user
3. Filters to be added after config-manager object is created to reduce hitting Database with multiple queries
4. Currently, user specified Filter is not supported for Custom-Query validate??
   i. Add filter support
   ii. Add the partition filter in the query itself

Later:
1. Add multiple partition logics: Primary key, Mod + Primary Key, Hash + Primary key + Mod, Hash + Mod
