### ISSUE TITLE
output list fields stdout column validation not having group_by_column

### ISSUE THREAD

**Issue by Hernan-V** [GoogleCloudPlatform/professional-services-data-validator#631]
When executing a validation with the last releases the output is restricted
![image](https://user-images.githubusercontent.com/34578114/200385269-c20ddb93-6453-40c3-bb39-146fc858d986.png)

But when executing it with version 1.7.2 the output have more columns:
![image](https://user-images.githubusercontent.com/34578114/200385440-c49015ad-f062-4c13-bcfa-ec103caf0527.png)

This can be controlled by --format or any other variable?
I can't find anything about it.

**Comment by nehanene15** [comment]
We filtered the column list further since for most validations we recommend using the BigQuery result handler. If you want to add/remove columns from the stdout data frame, you can edit the list [here](https://github.com/GoogleCloudPlatform/professional-services-data-validator/blob/develop/data_validation/consts.py#L139) - The COLUMN_FILTER_LIST is excluded in the final output.

**Comment by nehanene15** [comment]
Feel free to re-open if there is a follow up.
