### ISSUE TITLE
Format code in accordance to Google Python Style guide

### ISSUE THREAD

**Issue by nehanene15** [GoogleCloudPlatform/professional-services-data-validator#634]
- Format and optimize code to meet python style guide
- Clean up unnecessary comments and add comments where needed
- Optimize functions/code where necessary

Includes PR #5 to type check functions.

**Comment by nehanene15** [comment]
When debugging, there's a cyclic dependency since folder data_validation is the same name as file data_valiadation.py
We should rename the file to avoid this dependency

**Comment by mohdt786** [comment]
### Work around for cyclic imports while Debugging (Without editing the code)

**The issue is encountered while running command:**


```
python data_validation/__main__.py  [--arguments]
```

Error Encountered:

```
Traceback (most recent call last):
  File "/usr/local/google/home/mohammedturky/Development/professional-services-data-validator/data_validation/__main__.py", line 23, in <module>
    from data_validation import (
  File "/usr/local/google/home/mohammedturky/Development/professional-services-data-validator/data_validation/data_validation.py", line 24, in <module>
    from data_validation import combiner, consts, metadata
ImportError: cannot import name 'combiner' from partially initialized module 'data_validation' (most likely due to a circular import) (/usr/local/google/home/mohammedturky/Development/professional-services-data-validator/data_validation/data_validation.py)
```

1. **Work around via terminal:**

Instead of using execute file command, use execute module command

```
python -m data_validation.__main__ [--arguments]
```
This helps executing a local package containing absolute or relative imports without needing to install it
**Note:** Make sure cwd is `professional-services-data-validator` for the above command

2. **Debugging via VS Code:**

In Config file of debugger: launch.json, instead of `program` variable, use `module` variable
Example: launch.json

```
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "validate row",
            "type": "python",
            "request": "launch",
            "module": "data_validation.__main__", //No need to pass -m argument
            "console": "integratedTerminal",
            "justMyCode": true,
            "args":[
                    "validate", "row", 
                    "-sc", "BQ_CONN", 
                    "-tc", "BQ_CONN", 
                    "-tbls", "bigquery-public-data.new_york_citibike.citibike_stations", 
                    "--primary-keys", "station_id", 
                    "--hash", "*",
                    "--filters", "station_id>4000:station_id>4000",
                    ]
        }
    ]
}
```

**Comment by nehanene15** [comment]
Closing as much of this has been reformatted with the Ibis upgrade #894
