### ISSUE TITLE
Multiple columns having"id" in their name

### ISSUE THREAD

**Issue by vladutdinu** [GoogleCloudPlatform/professional-services-data-validator#635]
Hello, I've uploaded some data to a MySQL DB on a Linux env and tried some commands to play with the validation too. The problem that I encountered is that if the tables has multiple columns with "id" in their names it gets the first column returned.

I dont know whats the problem but i suspect the column selection is based on wildcards and maybe thats the problem, also I've seen some code in the project that transforms the column names to lowercase.

Here is the result of running the command:
![bugpic1](https://user-images.githubusercontent.com/48055925/203780772-d9e95c10-0ac5-44a1-bb14-b0dbdaf53c89.png)

I must mention that the table schema has a "id" column and a "caseID" column and both tables "logs" and "logs1" are the same.

Also, the result of running the validation command using all columns.
![bugpic2](https://user-images.githubusercontent.com/48055925/203781279-4866a8ab-4a0a-4049-89d5-4d9c5dec377d.png)

**Comment by nehanene15** [comment]
Hi,

If you pass in certain columns i.e -count 'caseID', it should only validate that column and populate the column name in 'source_column_name'. If source_column_name is blank (seen in the first screenshot), it is the result of the default count(*) validation. DVT may not be picking up the 'caseID' if the column is not numeric or string value which it will flag if you enable --verbose output.

You are also not comparing logs and logs1 but instead logs to itself and logs1 to itself. The correct syntax for comparing against each other would be `-tbls schema.logs=schema1.logs1` as described [here](https://github.com/GoogleCloudPlatform/professional-services-data-validator#column-validations).

The second screenshot is interesting since a -count '*' should not be getting individual column names so I'm unsure how that error would be generated. Are you using the latest version of the tool?

**Comment by vladutdinu** [comment]
Hello, thanks for the answers ! I will look into them ASAP.

Regarding the second screenshot, yes, I was using the latest version from that day.

**Comment by nehanene15** [comment]
Let me know if this is still an issue or if it can be closed.
