### ISSUE TITLE
validate row: Oracle NUMBER with scale doesn't match PostgreSQL DECIMAL with scale

### ISSUE THREAD

**Issue by nj1973** [GoogleCloudPlatform/professional-services-data-validator#685]
Fractional NUMBER column values do not match equivalent values in PostgreSQL due to differences in CAST behaviour.

For example, in Oracle:
```
SELECT CAST(CAST(100 AS NUMBER(5,2)) AS VARCHAR2(10)) FROM dual;

CAST(CAST(
----------
100
```

PostgreSQL equivalent:
```
# SELECT CAST(CAST(100 AS DECIMAL(5,2)) AS VARCHAR(10));
 varchar
---------
 100.00
```

The upshot of this is row data mismatches when using default validation type `cast` behaviour.

A suggested workaround for this specific Oracle to PostgreSQL project is to edit the config YAML file and for each Oracle NUMBER column with scale > 0:

- Change type cast to `to_char`
- Add `default_to_char_fmt` of "99999999.99" (matching p and s with the number of 9s)

The project is to migrate 1000s of database therefore a manual process is not viable. Also the workaround only works for this specific combination of source/target engines because Oracle and PostgreSQL share number formatting masks. An MSSQL to PostgreSQL project could still be a problem.

This is very similar to issue 680 (https://github.com/GoogleCloudPlatform/professional-services-data-validator/issues/680) but I've raised it as an independent issue because there is no common alternative already coded. Issue 680 can utilise existing `strftime`  functionality. This issue either needs a new engine agnostic alternative to cast or engine specific code to say "if the source and target are Oracle/PostgreSQL then use to_char and build a suitable mask".

**Comment by nehanene15** [comment]
This would also require us to track the column data type since we only want to replace cast with to_char if the column is a decimal/number column. An alternative here is to run column validation (SUM, AVG, etc) instead of row level where we need to hash a string value. Column validation would provide the same accuracy. 

Otherwise we would need Oracle to Postgres specific code.

**Comment by nj1973** [comment]
New plan is to align PostgreSQL CAST() behaviour with most other engines by using the TRIM_SCALE() function. This will trim off any unnecessary zero padding from the scale.

**Comment by nj1973** [comment]
The TRIM_SCALE() function was introduced in PostgreSQL 13. Versions 11 and 12 are still supported so I need to rethink this strategy.

**Comment by nehanene15** [comment]
Could we use the TO_CHAR() for decimals with a specific format? We also support the round() function.

Another option is to add the calculated field in the orchestration of DVT - i.e. in the YAML generation process add calculated fields for to_char() or round() for decimal columns instead of in the DVT code

**Comment by nj1973** [comment]
Yes, I've used TO_CHAR() for decimals with a specific format as you suggest. We can use `FM` in the format to remove any unnecessary padding.
