### ISSUE TITLE
MSSQL vs BQ - Column validation - Custom Query with max, count fails

### ISSUE THREAD

**Issue by madhu-jain** [GoogleCloudPlatform/professional-services-data-validator#717]
Column validation with custom query is not working for count, max etc

**Command Used :** 

data-validation validate custom-query \
--custom-query-type column \
--source-query-file ss_cust_max_src.sql \
--target-query-file ss_cust_max_tgt.sql \
-sc MSSQL_CONN \
-tc BQ_CONN \
--bq-result-handler paras-sandbox-364713.data_validator.results \
--max order_amount

data-validation validate custom-query \
--custom-query-type column \
--source-query-file ss_cust_max_src.sql \
--target-query-file ss_cust_max_tgt.sql \
-sc MSSQL_CONN \
-tc BQ_CONN \
--bq-result-handler paras-sandbox-364713.data_validator.results \
--count custid

Source query (ss_cust_max_src.sql) : select custid,order_amount from tempdb.dbo.customer;
Target query (ss_cust_max_tgt.sql) : select custid,order_amount from paras-sandbox-364713.dlp.customer;

**Error :** 

KeyError: <class 'decimal.Decimal'>

**Comment by kinchit9k** [comment]
@madhu-jain I am facing similar issue. Have you found any solution?

> The columns are originally stored in numeric/money in SQL server. I am trying to cast them in numeric(38,10) and then compare with BQ but end up with the same error. Table without numeric/money column works fine.

**Comment by kinchit9k** [comment]
I feel the problem might be because of the mapping mentioned in _get_schema_using_query in `/lib/python3.8/site-packages/third_party/ibis/ibis_mssql/client.py`, there is no reference provide in `type_map` for decimal.Decimal and also, I was unable to find any reference for timestamp although it is mentioned in  `type_map`. Any idea how can I added reference to it? 
@nehanene15 @sharangagarwal If you guys can take a look, it would be a great help.

**Comment by kinchit9k** [comment]
@madhu-jain Add `import decimal` to import decimal lib and `decimal.Decimal: 'Decimal',`  in type_map in `_get_schema_using_query` . it will work.
![image](https://user-images.githubusercontent.com/22678744/219278780-7231004a-618e-4d17-b2a9-60375532745a.png)

**Comment by nehanene15** [comment]
Closed with #771
