### ISSUE TITLE
Comparison, concat and hash functions for the same field are failing for MySQL

### ISSUE THREAD

**Issue by helensilva14** [GoogleCloudPlatform/professional-services-data-validator#820]
**[Problem externally pointed out by an user]** 

- This one is successful

`data-validation -v -ll=INFO validate row  --source-conn SOURCE -tc bq --tables-list SOURCE_TABLE=TARGET_TABLE --comparison-fields='amount' --primary-keys=id --format=json -bqrh BQ_PROJECT.pso_data_validator.results  --format=json --filters="id=10002992”`

- Now I change it to just do a --concat on the same exact field and the validation failed

`data-validation -v -ll=INFO validate row  --source-conn SOURCE -tc bq --tables-list SOURCE_TABLE=TARGET_TABLE --concat='amount' --primary-keys=id --format=json -bqrh BQ_PROJECT.pso_data_validator.results  --format=json --filters="id=10002992"`

- Now I change it to do a --hash on the same exact field. This one also fails

`data-validation -v -ll=INFO validate row  --source-conn SOURCE -tc bq --tables-list SOURCE_TABLE=TARGET_TABLE --hash='amount' --primary-keys=id --format=json -bqrh BQ_PROJECT.pso_data_validator.results  --format=json --filters="id=10002992"`

It doesn’t make any sense that a comparison of a field is successful but a hash and concat of the same exact field fails.

**Comment by piyushsarraf** [comment]
@helensilva14 
Regarding question "It doesn’t make any sense that a comparison of a field is successful but a hash and concat of the same exact field fails?" 

In comparison fields we take the source and target value and compare it as it is, but in concat or hash we do some sanitisation like casting to string, checking for nulls, and doing rtrim etc. and then concatenate the string to generate hash.

**Comment by piyushsarraf** [comment]
In my testing both hash and concat seems to be working fine, I tested with id and amount table with id as INT and amount as BIGINT in mysql and both as Integer in BQ and concat, hash, comp-fields are working fine. PFA the screenshots. 
![image](https://github.com/GoogleCloudPlatform/professional-services-data-validator/assets/47020544/bd7251f3-f582-4660-a0d9-96a17e3623be)
![image](https://github.com/GoogleCloudPlatform/professional-services-data-validator/assets/47020544/29cfcd01-c035-4b41-a3a4-14ad22684616)
![image](https://github.com/GoogleCloudPlatform/professional-services-data-validator/assets/47020544/25e204e9-4539-4abf-bf83-e683bef8db06)

Only datatypes like Datetime and Timestamp were incorrectly formatted earlier, which is fixed in #840.

**Comment by helensilva14** [comment]
@piyushsarraf That's great! I think we can ask for the user/customer to retry the validations with the version available on develop to confirm if everything is solved! What do you think @nehanene15 @Raniksingh?

**Comment by Raniksingh** [comment]
Right! we can ask the user to try with the develop branch.

**Comment by piyushsarraf** [comment]
Hi @helensilva14,
can we close this issue?

**Comment by helensilva14** [comment]
Sure, closing here and if needed you can re-open later.
