### ISSUE TITLE
Enhancement request: Add support for password-less connections to Oracle and PostgreSQL

### ISSUE THREAD

**Issue by simonpane** [GoogleCloudPlatform/professional-services-data-validator#825]
Some environments prohibit saving database passwords in configuration files, including the `${HOME}/.config/google-pso-data-validator/*.connection.json` files.

Oracle database connections can be made password-less using an Oracle Wallet and a "_secure external password store_" connection.  The **cx_Oracle** Python extension module supports this type of connection.  See: https://cx-oracle.readthedocs.io/en/latest/user_guide/connection_handling.html#connecting-using-external-authentication

Similarly, PostgreSQL connections via the **psycopg2** module should be able to use PostgreSQL "_trust_"ed connections (meaning no password authentication).  See: https://www.postgresql.org/docs/current/auth-pg-hba-conf.html

However, this toolkit errors if the password (and username) is not supplied when running `data-validation connections add ...`.

**Can this tool be enhanced for additional security by not requiring plain-text passwords in commands and configuration (json) files?**  And without having to use the GCP secrets manager?  Thanks

**Comment by nj1973** [comment]
Hi @simonpane, apologies we haven't progressed this issue yet. Hopefully you already saw that we added Oracle Wallet support.
For PostgreSQL trusted connections have you already tested with psycopg2 and proved that a passwordless connection works? If so was it as simple as omitting the username/password parameters? If the answer is "yes" then you might have some success editing the connection json file directly.

**Comment by helensilva14** [comment]
Thanks you @nj1973! On top of it, just wanted to highlight a few things:

1. @simonpane as you already shared with us, the authentication method change is implemented only in the `pg_hba.conf` file, which means `psycopg2` isn't able to perform this change and so it doesn't provide a direct way/param to specify it. So far, the only way we could see it working is how @nj1973 described above
2. The `trust` auth-method is very permissive as it already states in the documentation itself "_Allow the connection unconditionally. This method allows anyone that can connect to the PostgreSQL database server to login as any PostgreSQL user they wish, without the need for a password or any other authentication_", so we would not recommend relying on this procedure if possible

Please let us know if you had different outcomes, otherwise it looks like DVT won't be able to support password-less connections to PostgreSQL without having to use the GCP secrets manager.

**Comment by simonpane** [comment]
Thanks for the update - glad to see the Oracle Wallet support!
