### ISSUE TITLE
Column like group_by_columns is missing for custom query validation output.

### ISSUE THREAD

**Issue by dmahto05** [GoogleCloudPlatform/professional-services-data-validator#861]
Hello Folks, 

Post last release. output for below command is limited.
data-validation validate custom-query row

We are missing some of the columns like group_by_columns and more.

```
data-validation validate custom-query row --source-query-file /home/deepakmahto/professional-services-data-validator/oracle/sql1.sql --target-query-file /home/deepakmahto/professional-services-data-validator/postgres/sql1.sql  -sc ora_conn -tc pg_conn  --concat '*'  --primary-keys owner,object_type -fmt csv
validation_name,validation_type,source_table_name,source_column_name,source_agg_value,target_agg_value,pct_difference,validation_status,run_id
concat__all,Custom-query,,,,18_SAKILAINDEX,,fail,2cfbeb89-5b21-4753-b2a9-7eb6148b313e
concat__all,Custom-query,,,,18_SAKILATABLE,,fail,2cfbeb89-5b21-4753-b2a9-7eb6148b313e
concat__all,Custom-query,,,,3_SAKILATYPE,,fail,2cfbeb89-5b21-4753-b2a9-7eb6148b313e
```

It is impacting wrapper written on top of custom query with failure and limited functionality.

**Comment by nj1973** [comment]
This was caused by issue https://github.com/GoogleCloudPlatform/professional-services-data-validator/issues/753. The intention was to make `text` output consistent with the `fancy_grid` output. We've also removed extra columns from CSV and JSON output which is a mistake. We should reinstate those by reversing the CSV/JSON parts of this change:

https://github.com/GoogleCloudPlatform/professional-services-data-validator/commit/b92eb91feb3b4a83c6ad74c4b9c5af65dcbc21f8
