### ISSUE TITLE
Feature Request: remove upper limit for partition num size (or make it bigger)

### ISSUE THREAD

**Issue by florisvink** [GoogleCloudPlatform/professional-services-data-validator#966]
We often split large tables in partitions. To keep each generated partitioned config manageable to run at once we often have to create more than (the now max.) 1000 partitions. Currently I removed this limit from DVT myself but I guess it cannot hurt to (at least) make the maximum amount of partitions bigger? Currently we never go over 6000.

**Comment by nehanene15** [comment]
We'll need to update this to 6000 in these two areas of the code:

https://github.com/GoogleCloudPlatform/professional-services-data-validator/blob/15bfc4c85e43894f03288cf10aa7888a95342a05/data_validation/cli_tools.py#L967

https://github.com/GoogleCloudPlatform/professional-services-data-validator/blob/15bfc4c85e43894f03288cf10aa7888a95342a05/README.md?plain=1#L238

**Comment by sundar-mudupalli-work** [comment]
Hi,

Neha is right. We can increase the number of partitions to 10K by changing the following two lines in [cli_tools.py](https://github.com/GoogleCloudPlatform/professional-services-data-validator/blob/f51f32751bfb8713ac04de6456421a3d4a8ff1ce/data_validation/cli_tools.py#L983):
```
        choices=range(1, 1001),
        metavar="[1-1000]",
```
basically change the limits to 10001 and 10000.
To increase the number of partitions higher - say to 1M partitions - we would need to change the number of characters we use for the name of the yaml files. Currently we use 4 characters - so can do `0000.yaml` to `9999.yaml`. For 1M partitions we would need to use 6 characters, so that we can do `000000.yaml` to `999999.yaml`. I suggest that we pause on this change in DVT - since it is more complex. 
First, we would need to change the way we generate the file names. So this line in [partition_builder.py](https://github.com/GoogleCloudPlatform/professional-services-data-validator/blob/f51f32751bfb8713ac04de6456421a3d4a8ff1ce/data_validation/partition_builder.py#L336):
```
                target_file_name = "0" * (4 - len(str(pos))) + str(pos) + ".yaml"
```
could be rewritten as:
```
                target_file_name = f"{pos:06d}.yaml"
```
We will also need a change in how we process files in directories if DVT is run via cloud run jobs or K8 - see [`__main__.py`](https://github.com/GoogleCloudPlatform/professional-services-data-validator/blob/f51f32751bfb8713ac04de6456421a3d4a8ff1ce/data_validation/__main__.py#L351C1-L355C14). There we currently look for file names from `0000.yaml` to `9999.yaml`. We would need to see if the directory contains these files (old `generate-table-partitions` behavior) or from `000000.yaml` to `000000.yaml` (new `generate-table-partitions` behavior). That is these lines:
```
            config_file_path = (
                f"{args.config_dir}{job_index:04d}.yaml"
                if args.config_dir.endswith("/")
                else f"{args.config_dir}/{job_index:04d}.yaml"
            )
```
We would also need to test this and will likely need to run DVT on a node with at least 16GB memory to partition a table into 1M partitions. `generate-table-partitions` could run out of memory - since it is handling 1M rows in memory with the partition information.

Sundar Mudupalli

**Comment by sundar-mudupalli-work** [comment]
Hi,

Closing this as a duplicate of [#1137](https://github.com/GoogleCloudPlatform/professional-services-data-validator/issues/1137). 

Thanks.

Sundar Mudupalli
